//#region SIGNIN
export const SIGNIN_FAIL = "SIGNIN_FAIL";
export const SIGNIN_START = "SIGNIN_START";
export const LOGOUT = "LOGOUT";
export const SIGNIN_SUCCESS = "SIGNIN_SUCCESS";
//#endregion

//#region SIGNUP
export const SIGNUP_FAIL = "SIGNUP_FAIL";
export const SIGNUP_START = "SIGNUP_START";
export const SIGNUP_SUCCESS = "SIGNUP_SUCCESS";
//#endregion

//#region PIZZA
export const GET_ALL_PIZZA_FAIL = "GET_ALL_PIZZA_FAIL";
export const GET_ALL_PIZZA_START = "GET_ALL_PIZZA_START";
export const GET_ALL_PIZZA_SUCCESS = "GET_ALL_PIZZA_SUCCESS";
//#endregion

//#region CART
export const ADD_PIZZA_TO_CART = "ADD_PIZZA_TO_CART";
export const REMOVE_PIZZA_FROM_CART = "REMOVE_PIZZA_FROM_CART";
export const UPDATE_PIZZA_ON_CART_IF_EXISTS = "UPDATE_PIZZA_ON_CART_IF_EXISTS";
//#endregion

//#region ORDER
export const GET_USER_ORDERS_START = "GET_USER_ORDERS_START";
export const GET_USER_ORDERS_FAIL = "GET_USER_ORDERS_FAIL";
export const GET_USER_ORDERS_SUCCESS = "GET_USER_ORDERS_SUCCESS";
export const UPDATE_PIZZA_ON_CART_QUANTITY = "UPDATE_PIZZA_ON_CART_QUANTITY";
export const UPDATE_ORDER_SERIAL_ID = "UPDATE_ORDER_SERIAL_ID";
export const UPDATE_ORDER_NAME = "UPDATE_ORDER_NAME";
export const UPDATE_ORDER_ADDRESS = "UPDATE_ORDER_ADDRESS";
export const UPDATE_ORDER_DELIVERY_COST = "UPDATE_ORDER_DELIVERY_COST";
//#endregion
